[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(sbtMapExec 11 __bfb4f999-e640-4853-abaf-9f39774d1f48, None, None)
[debug] > Exec(bspBuildTargetCompile file:/Users/nakul_rao/Desktop/School/West%20Point/CS%20384/AOC/#aoc/Compile, Some(__bfb4f999-e640-4853-abaf-9f39774d1f48), Some(CommandSource(network-28)))
[debug] jsonRpcNotify: JsonRpcNotificationMessage(2.0, build/logMessage, {"type":4,"message":"Processing"})
[debug] Evaluating tasks: bspBuildTargetCompile
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[warn] Canceling execution...
[debug] Forcing garbage collection...
[debug] jsonRpcNotify: JsonRpcNotificationMessage(2.0, shutdown, [false,null])
[debug] jsonRpcNotify: JsonRpcNotificationMessage(2.0, shutdown, [true,null])
[error] java.util.concurrent.RejectedExecutionException
[error] 	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
[error] 	at sbt.Execute.submit(Execute.scala:282)
[error] 	at sbt.Execute.ready(Execute.scala:262)
[error] 	at sbt.Execute.addNew(Execute.scala:235)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.$anonfun$addNew$3(Execute.scala:239)
[error] 	at sbt.Execute.$anonfun$addNew$3$adapted(Execute.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.internal.util.IDSet$$anon$1.foreach(IDSet.scala:44)
[error] 	at sbt.Execute.addNew(Execute.scala:238)
[error] 	at sbt.Execute.addChecked(Execute.scala:211)
[error] 	at sbt.Execute.call(Execute.scala:147)
[error] 	at sbt.Execute.$anonfun$work$2(Execute.scala:300)
[error] 	at sbt.Execute$$anon$1.process(Execute.scala:27)
[error] 	at sbt.Execute.next$1(Execute.scala:117)
[error] 	at sbt.Execute.processAll(Execute.scala:127)
[error] 	at sbt.Execute.runKeep(Execute.scala:95)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:476)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:475)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:498)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
[error] 	at sbt.Command$.process(Command.scala:189)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:244)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:244)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:268)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:162)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:143)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:190)
[error] 	at sbt.xMain$.$anonfun$run$8(Main.scala:102)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:557)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:347)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:547)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:547)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:347)
[error] 	at sbt.xMain$.run(Main.scala:86)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
[error] 	at sbt.xMain.run(Main.scala:46)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:120)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.concurrent.RejectedExecutionException
[error] Use 'last' for the full log.
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(sbtPopOnFailure, None, None)
[debug] > Exec(sbtReportResult 11, Some(11), Some(CommandSource(network-28)))
[debug] > Exec(shell, None, None)
